import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadExerciseManifest } from "../packages/shared/src/exercise-manifest.ts";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const exercisesRoot = path.join(repoRoot, "exercises");
const outputDir = path.join(repoRoot, "packages/web/src/generated");
const outputFile = path.join(outputDir, "exercises-data.ts");

const readStarterFiles = async (slug: string, filesToOpen: string[]) => {
  const exerciseDir = path.join(exercisesRoot, slug);
  const entries = await Promise.all(
    filesToOpen.map(async (filePath) => [
      filePath,
      await readFile(path.join(exerciseDir, filePath), "utf8"),
    ]),
  );

  return Object.fromEntries(entries);
};

const entries = await readdir(exercisesRoot, { withFileTypes: true });
const exercises = await Promise.all(
  entries
    .filter((entry) => entry.isDirectory())
    .map(async (entry) => {
      const manifest = await loadExerciseManifest(
        path.join(exercisesRoot, entry.name, "exercise.json"),
      );
      const files = await readStarterFiles(manifest.slug, manifest.filesToOpen);

      return {
        slug: manifest.slug,
        title: manifest.title,
        language: manifest.language,
        filesToOpen: manifest.filesToOpen,
        studentFiles: manifest.studentFiles,
        readme: manifest.readme,
        files,
      };
    }),
);

const summaries = exercises.map(({ slug, title }) => ({ slug, title }));

await mkdir(outputDir, { recursive: true });
await writeFile(
  outputFile,
  `// Generated by scripts/generate-static-exercises.mts — do not edit.\nexport const staticExerciseSummaries = ${JSON.stringify(summaries, null, 2)} as const;\n\nexport const staticExercises = ${JSON.stringify(exercises, null, 2)} as const;\n`,
  "utf8",
);

console.log(`Wrote ${exercises.length} exercise(s) to ${outputFile}`);
