import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadQuizManifest, toCategorizedQuizSummary } from "../packages/shared/src/quiz-manifest.ts";
import { toPublicQuizDetail } from "../packages/shared/src/quiz-check.ts";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const quizzesRoot = path.join(repoRoot, "quizzes");
const outputDir = path.join(repoRoot, "packages/web/src/generated");
const outputFile = path.join(outputDir, "quizzes-data.ts");

const entries = await readdir(quizzesRoot, { withFileTypes: true });
const loaded = await Promise.all(
  entries
    .filter((entry) => entry.isDirectory())
    .map(async (entry) => {
      const manifest = await loadQuizManifest(
        path.join(quizzesRoot, entry.name, "quiz.json"),
      );
      return {
        summary: toCategorizedQuizSummary(manifest),
        detail: toPublicQuizDetail(manifest),
        manifest,
      };
    }),
);

const summaries = loaded.map(({ summary }) => summary);
const quizzes = loaded.map(({ detail }) => detail);
const quizManifests = loaded.map(({ manifest }) => manifest);

await mkdir(outputDir, { recursive: true });
await writeFile(
  outputFile,
  `// Generated by scripts/generate-static-quizzes.mts — do not edit.\nexport const staticQuizSummaries = ${JSON.stringify(summaries, null, 2)} as const;\n\nexport const staticQuizzes = ${JSON.stringify(quizzes, null, 2)} as const;\n\nexport const staticQuizManifests = ${JSON.stringify(quizManifests, null, 2)} as const;\n`,
  "utf8",
);

console.log(`Wrote ${quizzes.length} quiz(zes) to ${outputFile}`);
